<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center mb-4">
          <img src="/img/twitter_logo.png" alt="Twitter logo">
        </div>

        <div class="row mb-3">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="" method="post">

              <div class="mb-3">
                <input type="text" class="form-control" placeholder="Nome">
              </div>

              <div class="mb-3">
                <input type="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="mb-3">
                <input type="password" class="form-control" placeholder="Senha">
              </div>

              <div class="mt-4 mb-4">
                <small class="text-muted">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as
                  Políticas de Privacidade, incluindo o Uso de Cookies. Outras
                  pessoas poderão encontrar você pelo e-mail ou número de telefone
                  fornecido · Opções de Privacidade
                </small>
              </div>

              <button type="submit" class="btn btn-primary w-100">
                Inscrever-se
              </button>

            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
