<h1>Sobre Nos</h1>

<hr>

<?php foreach ($this->view->dados as $indice => $info) { ?>
    <h1><?= $info['titulo'] ?> </h1>
    <br>
    <?= $info['descricao'] ?>
    <hr>

<?php } ?>



<?php
// echo '<pre>';
// print_r($this->view->dados);
// echo '</pre>';

// foreach ($this->view->dados as $indice => $info) {
//     echo '<h1>' . $info['titulo'] . '</h1>';
//     echo '<br>';
//     echo $info['descricao'];
//     echo '<hr>';

// }
// echo 'Chegamos ao IndexController e disparamos a action sobreNos';

?>